# docker-Specify the compose version
version: "3"

services:
  app:
    # build: .
    image: pudding/docker-image-base:action-UT-Podcast-Docker-Image-20240806.193744
    tty: true
    volumes: 
      - ./output:/output/
      - ./cache:/cache/
      - ./config-list.js:/config-list.js
      - ./config-json.js:/config-json.js
